// `import type` here is deliberate, not stylistic: interview-service.ts
// (in the ../interview package) imports answerGenerationService from this
// package, so a plain value import here would create a real circular
// runtime dependency between the two packages. Both of these are used in
// type position only (an interface extends clause, a `typeof` query), so
// `import type` guarantees they're erased at compile time — no runtime
// import exists in either direction, only a one-way interview -> interview-ai
// dependency remains at runtime.
import type { InterviewExtractionResult, InterviewQuestion } from "../interview";
import type { DIFFICULTY_LEVELS, EXPERIENCE_LEVELS } from "./answer-schema";

export type Difficulty = (typeof DIFFICULTY_LEVELS)[number];
export type ExperienceLevel = (typeof EXPERIENCE_LEVELS)[number];

/**
 * A Milestone 1 InterviewQuestion, optionally enriched with Milestone 2's
 * AI-generated fields. The enrichment fields are only present when
 * `aiGenerated` is true (i.e. this question had no answer and one was
 * generated) — a question that already had an answer in the source
 * document is returned unchanged (`aiGenerated: false`), per the
 * "never overwrite existing answers" rule. This is a pure additive
 * extension — Milestone 1's InterviewQuestion type itself is untouched.
 */
export interface EnrichedInterviewQuestion extends InterviewQuestion {
  shortAnswer?: string;
  codeExample?: string;
  difficulty?: Difficulty;
  experienceLevel?: ExperienceLevel;
  importantConcepts?: string[];
  commonMistakes?: string[];
  followUpQuestions?: string[];
  bestPractices?: string[];
  tags?: string[];
  /** true only when this question's answer was generated by this milestone, not found in the source document. */
  aiGenerated: boolean;
}

/** The Milestone 1 InterviewExtractionResult, with `questions` upgraded to EnrichedInterviewQuestion[]. */
export interface EnrichedInterviewDocument extends Omit<InterviewExtractionResult, "questions"> {
  questions: EnrichedInterviewQuestion[];
}
