-- Phase 11.5 — Enterprise Interview Document Intelligence
--
-- Adds two optional columns to the existing `interview_questions` table so
-- Admin Review can record, per question, whether its answer came verbatim
-- from the uploaded document or was AI-generated, and how confident the
-- extraction pipeline was in the overall import batch.
--
-- This repo has no migration tooling (no supabase/ CLI project, no `pg`
-- dependency — all DB access goes through PostgREST via the JS client,
-- which cannot run DDL). Run this file manually once, in the Supabase
-- SQL Editor for this project, before using Admin Review's persistence of
-- answerSource/qualityScore. Everything else in Phase 11.5 works without
-- it — the import path detects whether these columns exist and silently
-- skips writing them if this migration hasn't been applied yet.
--
-- Safe to re-run: IF NOT EXISTS makes this idempotent.

alter table interview_questions
  add column if not exists answer_source text
    check (answer_source in ('ORIGINAL', 'GENERATED'));

alter table interview_questions
  add column if not exists quality_score numeric;

comment on column interview_questions.answer_source is
  'Whether this answer was preserved verbatim from the uploaded document (ORIGINAL) or generated by AI because the document had none (GENERATED). Set by the Phase 11.5 Interview Document Intelligence import pipeline.';

comment on column interview_questions.quality_score is
  'Extraction quality score (0-100) for the import batch this question came from. Set by the Phase 11.5 Interview Document Intelligence import pipeline.';
